### ISSUE TITLE
What template do you use for awesome-r.com?

### ISSUE THREAD

**Issue by sillasgonzaga** [qinwf/awesome-R#101]
Not quite an issue, just a simple question.

The template reminds me of [bookdown](https://bookdown.org/yihui/bookdown/), but there are some differences. Is it a customized CSS?

**Comment by qinwf** [comment]
There is a note [here](https://github.com/qinwf/awesome-R/tree/gh-pages#readme).

The page uses [flatdoc](https://github.com/rstacruz/flatdoc) to render markdown.

**Comment by sillasgonzaga** [comment]
Thanks.
