### ISSUE TITLE
how about some spatial libraries?

### ISSUE THREAD

**Issue by tim-salabim** [qinwf/awesome-R#105]
You mention `library(leaflet)` (which starts with a smal 'l' btw) which is a mapping library, but I don't see any mention of other spatial libraries such as `sp` or `raster`. If you look at the download rates of these libraries, I would assume they are well worth pointing out here... That is, of course, only relevant if you understand awesome-R to be an objective list.

**Comment by qinwf** [comment]
The page on the [docs](http://rstudio.github.io/leaflet/) page, it shows `Leaflet for R`, though the package name in R is `leaflet`. This package is on HTML Widgets section.

I am not very familar with Spatial Statistics. Contribution for this new section will be wonderful!
