### ISSUE TITLE
is this list still maintained?

### ISSUE THREAD

**Issue by randy3k** [qinwf/awesome-R#145]
I totally understand if @qinwf maybe busy with your own things. However, the slow response rate of this repo is somewhat disappointing. There are a number of PRs waiting to be reviewed for ages. 

How about the idea of moving it to an organization and recruit some members for helping to maintain the list, or recruit some collaborators to monitor it? Given the number of stars and forks, I am sure that there should be a number of people who are interested in moderating this (I am one of them).

**Comment by qinwf** [comment]
Yes, I am maintaining it.
