### ISSUE TITLE
Links to CRAN views would be useful

### ISSUE THREAD

**Issue by ottadini** [qinwf/awesome-R#62]
The list of packages for machine learning could be improved with links to the R views like 'MachineLearning', and 'Cluster'. I originally put self-organising maps here (hence the title originally having 'kohonen'), but perhaps that's not quite machine learning enough?

**Comment by qinwf** [comment]
"kohonen" is added. 

There is a link to CRAN task views in Website section.

 If you think some other packages are good, you can always create pull request.
