### ISSUE TITLE
Add R Markdown

### ISSUE THREAD

**Issue by demidovakatya** [qinwf/awesome-R#72]
[R Markdown](http://rmarkdown.rstudio.com) – An authoring format that enables easy creation of dynamic documents, presentations, and reports from R.

**Comment by qinwf** [comment]
It is on https://github.com/qinwf/awesome-R#reproducible-research .

**Comment by demidovakatya** [comment]
my bad! 🙈

**Comment by qinwf** [comment]
Thanks anyway~
