### ISSUE TITLE
Add useR conferences and/or groups?

### ISSUE THREAD

**Issue by briatte** [qinwf/awesome-R#93]
* https://www.r-project.org/conferences.html
* http://blog.revolutionanalytics.com/user-groups/

**Comment by qinwf** [comment]
Thanks.
I suggest to add [User Groups Link](http://blog.revolutionanalytics.com/user-groups/) to [Posts](https://github.com/qinwf/awesome-R/blob/master/posts.md). It seems to be a series of blog posts.

**Comment by briatte** [comment]
Apologies for forgetting to close the issue myself.
